model = "gpt-5.4"
model_reasoning_effort = "xhigh"
service_tier = "fast"
# approval_policy = "never"
# sandbox_mode = "danger-full-access"
model_context_window = 1000000
model_auto_compact_token_limit = 900000
